#!/bin/bash
# 
# WARNING - script under development.
#           Building RPMs with use of alien
#           Works for main library but not yet -dev one but useful proof of concept
#	    Resonable rpmlint result. rpmling is not as mature as lintian !
#
#	    David Bannon 2022-11-23
#
# Ugly script to package the libqt6pas library for debian.
# Note : 
#	* Based on Lazarus trunk version, its 6.2.3 for now. 

#	David Bannon, LGPL with exception, see associated COPYING.TXT 
#	package names look like this (qt5 eg) -

# intel	libqt5pas1_2.10-0_amd64.deb  		dest = /usr/lib/x86_64-linux-gnu
#	libqt5pas-dev_2.10-0_arm64.deb 

# arm64	libqt5pas-dev_2.10-0_amd64.deb 		dest = 
# 	libqt5pas1_2.10-0_arm64.deb 

# arm32	libqt5pas1_2.10-0_armhf.deb 		dest = /usr/lib/arm-linux-gnueabihf
#	libqt5pas-dev_2.10-0_armhf.deb    


PACKVER='1'		# should start at '1', rev if you re-package same binary

LIBNAME=libQt6Pas



CURRENT=`pwd`

if [ -f "../version" ]; then
	VERSION=`cat ../version`
	MAJORVER=`echo $VERSION | awk -F"." '{ printf $1 }'`	# for 6.1.0,  MAJORVER=6
	MINORVER=`echo $VERSION | awk -F"." '{ printf $2 }'`	# for 1.2.8,  MINORVER=2
	EXTRAVER=`echo $VERSION | awk -F"." '{ printf $3 }'`	# for 1.2.8,  MINORVER=8
else
	# library will be called something like ./libQt6Pas.so.6.2.3
	cd ..
	LIBFILE=$(find . -maxdepth 1 ! -type l  -name "$LIBNAME""*")
	cd $CURRENT
	MAJORVER=`echo $LIBFILE | awk -F"." '{ printf $4 }'`
	MINORVER=`echo $LIBFILE | awk -F"." '{ printf $5 }'`
	EXTRAVER=`echo $LIBFILE | awk -F"." '{ printf $6 }'`
	VERSION="$MAJORVER"."$MINORVER"."$EXTRAVER"
fi
# echo "Name=""$LIBFILE"", Maj=""$MAJORVER"", Minor=""$MINORVER"", extra=""$EXTRAVER"
# ToDo : really should have some sanity checks here



PRODUCT="libqt6pas"	# note lib has upper case letters, this appears in Package name
FULLLIBNAME="$LIBNAME".so."$VERSION"

ARCH=unknown		# we will set further down. amd64  arm64 and armhf, note: arm64 aka aarch64 ? 
DIR_ARCH=unknown
M_ARCH=`uname -m`	# Might return, eg aarch64, x86_64. Raspi running 32bit returns armv7l - possibly RasPi version specific ?

VER1=`echo $VERSION | awk -F"." '{ printf $1 }'`		# ie "2"
VER2=`echo $VERSION | awk -F"." '{ printf $1"."$2 }'`		# ie "2.8"
#VER3=`echo $VERSION | awk -F"." '{ printf $2"."$3 }'`

WHOAMI="David Bannon <tomboy-ng@bannons.id.au>"
BUILDDATE=`date -R`

function WriteControl () {
	if [ "$1" = "DEV" ]; then
		echo "Package: $PRODUCT-dev" >> BUILD/DEBIAN/control			
	else
		echo "Package: $PRODUCT$MAJORVER" >> BUILD/DEBIAN/control
		# Next line should mention the source package name we don't have one yet.
		# https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
		# echo "Source: CHANGE-ME" >> BUILD/DEBIAN/control
	fi
	echo "Version: $MINORVER"."$EXTRAVER" >> BUILD/DEBIAN/control
	echo "Architecture: ""$ARCH" >> BUILD/DEBIAN/control
	echo "Maintainer: $WHOAMI" >> BUILD/DEBIAN/control
	echo "Priority: optional" >> BUILD/DEBIAN/control
	echo "Multi-Arch: same" >> BUILD/DEBIAN/control
	echo "Homepage: https://wiki.freepascal.org/Qt6_Interface" >> BUILD/DEBIAN/control
	# ----- I am not sure if the following is a good idea or not, no, better without, as is replaces old ver, might get new version next
	# echo "Replaces: libqt5pas1" >> BUILD/DEBIAN/control


	SIZE_IN_KB="$(du -s BUILD | awk '{print $1;}')"
	echo "Installed-Size: ${SIZE_IN_KB}" >> BUILD/DEBIAN/control

	if [ "$1" = "DEV" ]; then
		# echo "Installed-Size: 1445" >> BUILD/DEBIAN/control
		echo "Depends: $PRODUCT$MAJORVER (>= $MINORVER"."$EXTRAVER), qt6-base-dev" >> BUILD/DEBIAN/control
		echo "Section: libdevel" >> BUILD/DEBIAN/control
		echo "Description: Development files for Qt6Pas" >> BUILD/DEBIAN/control
	else

		# echo "Installed-Size: 3314" >> BUILD/DEBIAN/control
		echo "Depends: libc6 (>= 2.34), libgcc1 (>= 11.3), libqt6core6 (>= 6.2.3), libqt6gui6 (>= 6.2.3), libqt6printsupport6 (>= 6.2.3), libqt6widgets6 (>= 6.2.3), libstdc++6 (>= 5), qt6-qpa-plugins" >> BUILD/DEBIAN/control
		echo "Section: libs" >> BUILD/DEBIAN/control
		echo "Description: Qt6 interface bindings for Pascal" >> BUILD/DEBIAN/control
	fi
	echo " Provides interface for Pascal applications, is only" >> BUILD/DEBIAN/control
	echo " a temp hack until distributions catch up. It is" >> BUILD/DEBIAN/control
	echo " only really useful, at present, to people using"   >> BUILD/DEBIAN/control
	echo " Lazarus main, current release versions do not need it." >> BUILD/DEBIAN/control
}


function DebianPackage () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/doc/"$PRODUCT$MAJORVER"
	WriteControl
	cp ../"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/.
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$FULLLIBNAME" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$MAJORVER"
	# Don't link to base name, Lintian objects 'cos thats the -dev package's job

	chmod 0644 BUILD/usr/lib/"$DIR_ARCH"/*
	
    	cp copyright "BUILD/usr/share/doc/$PRODUCT$MAJORVER/copyright"
	
	echo "activate-noawait ldconfig" > BUILD/DEBIAN/triggers
	echo "libQt6Pas $MAJORVER libqt6pas$MAJORVER" > BUILD/DEBIAN/shlibs
	gzip -knc --best changelog.libqt6pas >> BUILD/usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$VERSION" > DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT$MAJORVER"_"$MINORVER"."$EXTRAVER"-"$PACKVER"_"$ARCH".deb
}

function DebianPackageDev () {
	# We build a debian tree in BUILD and call dpkg-deb -b 
	rm -rf BUILD
	mkdir -p BUILD/DEBIAN
	mkdir -p BUILD/usr/lib/"$DIR_ARCH"
	mkdir -p BUILD/usr/share/pascal/qt6
	mkdir -p BUILD/usr/share/doc/"$PRODUCT"-dev
	WriteControl DEV
	ln -s -r BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so."$VERSION" BUILD/usr/lib/"$DIR_ARCH"/"$LIBNAME".so
	cp ../qt6.pas BUILD/usr/share/pascal/qt6/.
	cp ../qt62.pas BUILD/usr/share/pascal/qt6/.
	chmod 0644 BUILD/usr/share/pascal/qt6/*
    	cp copyright BUILD/usr/share/doc/"$PRODUCT-dev"/copyright
	gzip -knc --best changelog.libqt6pas >> BUILD/usr/share/doc/"$PRODUCT-dev"/changelog.gz
 
	# ------ Make the md5sum file -----------
	cd BUILD
	md5sum  "usr/share/pascal/qt6/qt6.pas" > DEBIAN/md5sums
	md5sum  "usr/share/pascal/qt6/qt62.pas" >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/copyright >> DEBIAN/md5sums
	md5sum  usr/share/doc/"$PRODUCT"-dev/changelog.gz >> DEBIAN/md5sums
	cd ..
	chmod -R g-w BUILD
  	fakeroot dpkg-deb -b BUILD/. "$PRODUCT"-dev_"$MINORVER"."$EXTRAVER"-"$PACKVER"_"$ARCH".deb
}

# A lot more work is required for this to work even on non amd64 hardware.
# Paricularly where the library is suposed to end up !
#

# We want a dir name like this - libqt6pas6-2.2

function MakeRPM () {
	FULLVER="$1"_"$2"."$3"-"$PACKVER"
        RDIR="$PRODUCT$1-$MINORVER"."$EXTRAVER"
        echo "=== Making RPM from $PRODUCT""$FULLVER"_"$ARCH.deb ==="
        rm -Rf "$RDIR"
	mkdir -p "$RDIR"/usr/share/doc/"$PRODUCT""$1"
	chmod 755 "$RDIR"/usr/share/doc/"$PRODUCT""$1"
	mkdir "$RDIR"/usr/"$RDIR_ARCH"
	cp ../"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/.
	ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"."$MINORVER"
	ln -s -r "$RDIR"/usr/"$RDIR_ARCH"/"$FULLLIBNAME" "$RDIR"/usr/"$RDIR_ARCH"/"$LIBNAME".so."$MAJORVER"
    	cp copyright "$RDIR/usr/share/doc/"$PRODUCT""$1"/copyright"
	gzip -knc --best changelog.libqt6pas >> "$RDIR"/usr/share/doc/"$PRODUCT$MAJORVER"/changelog.gz
	cp libqt6pas6-2.2-2.spec "$RDIR"/.
	cd "$RDIR"
	ls -la
	fakeroot rpmbuild --target "$M_ARCH" --buildroot "$CURRENT"/"$RDIR" -bb "$RDIR"-2.spec
	cd .. 
}


if [ "$M_ARCH" == "aarch64" ]; then
	ARCH="arm64"			# Name used in deb file name
	DIR_ARCH="aarch64-linux-gnu"	# Dir where the libraries end up
	RDIR_ARCH="ERROR"		# Where RPMs put the library         TODO !!!
fi
if [ "$M_ARCH" == "armv7l" ]; then
	ARCH="armhf"
	DIR_ARCH="arm-linux-gnueabihf"
	RDIR_ARCH="ERROR"		# Where RPMs put the library         TODO !!!
fi
if [ "$M_ARCH" == "x86_64" ]; then
	ARCH="amd64"
	DIR_ARCH="x86_64-linux-gnu"
	RDIR_ARCH="lib64"		# Where RPMs put the library 
fi
if [ "$ARCH" == "unknown" ]; then
	echo "ERROR cannot id your arch $DIR_ARCH, exiting..."
	exit
fi

echo "Building for $ARCH to go into $DIR_ARCH - Maj=""$MAJORVER"", Min=""$MINORVER"", EXTRA=""$EXTRAVER"

strip --remove-section=.comment ../libQt6Pas.so."$VERSION"

DebianPackage 
DebianPackageDev
echo " ====== Finished Building Debs ======="
MakeRPM "$MAJORVER" "$MINORVER" "$EXTRAVER"  
# ----------- RESTORE ME --------------- MakeRPM "-dev" "$MINORVER" "$EXTRAVER"       

TARNAME=libqt6pas_"$MAJORVER"_"$MINORVER"_"$EXTRAVER"-"$PACKVER"_"$ARCH"
rm -Rf "$TARNAME"
mkdir "$TARNAME"
cp ../targz.readme "$TARNAME"/.
cp ../libQt6Pas.so."$VERSION" "$TARNAME"/.
tar czf "$TARNAME".tar.gz "$TARNAME"
rm -Rf "$TARNAME"
rm -Rf BUILD
ls -ltr

# ------- RESTORE ME --------------- lintian -IiE *.deb

#echo " === OK, now make the rpms with   fakeroot bash ./rpm-package.bash   <enter> ==="


# --------------- RPM LINT Issues ------------------------------

# libqt6pas6.x86_64: E: library-without-ldconfig-postin
# libqt6pas6.x86_64: E: library-without-ldconfig-postun
#    Not required anymore =
#    https://fedoraproject.org/wiki/Changes/Removing_ldconfig_scriptlets

# libqt6pas6.x86_64: W: invalid-license see /usr/share/doc/libqt6pas6/copyright
#    The license is fine, its just that rpmlint cannot parse it.

# libqt6pas6.x86_64: W: spelling-error %description -l en_US distro -> bistro, distress
#    The value of this tag appears to be misspelled. Please double-check.
#    Appears to be complining about the %description - seems exactly how it should be.

# libqt6pas6.x86_64: E: no-changelogname-tag
#    There is a chanlog tag, exacly how its described. Apparenly a nonsence message ?

# libqt6pas6.x86_64: E: no-signature
#    As near as I can tell, only OpenSUSE seems to care about signitures.
                                                                                                        
